artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/b4e558358b734d0f829a4a17bbc8470d/artifacts
end_time: 1730227956829
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b4e558358b734d0f829a4a17bbc8470d
run_name: Default
run_uuid: b4e558358b734d0f829a4a17bbc8470d
source_name: ''
source_type: 4
source_version: ''
start_time: 1730227956818
status: 3
tags: []
user_id: mle-user
